import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    position: "relative",
    width: "100%",
    height: "auto",
  },
  form: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    width: "100%",
    height: "100%",
    maxHeight: "80px",
    background: "inherit",
    border: "inherit",
    borderRadius: "inherit",
    padding: "inherit",
    boxSizing: "border-box",
  },
  input: {
    flex: 1,
    minWidth: 0,
    height: "100%",
    //maxHeight: "120px",
    padding: "8px 12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderRadius: "6px 0 0 6px",
    fontSize: "14px",
    outline: "none",
    background: "#ffffff",
    boxSizing: "border-box",
  },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    minHeight: "36px",
    padding: 0,
    width: "40px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderLeft: "none",
    borderRadius: "0 6px 6px 0",
    background: "#f3f4f6",
    color: "#374151",
    cursor: "pointer",
    transition: "all 0.15s ease",
    boxSizing: "border-box",
    flexShrink: 0,
  },
  icon: {
    width: "20px",
    height: "20px",
    flexShrink: 0,
    display: "block",
    fill: "currentColor",
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: "4px",
    background: "#ffffff",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderRadius: "6px",
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    maxHeight: "300px",
    overflowY: "auto",
    zIndex: 1000,
  },
  resultItem: {
    padding: "12px 16px",
    cursor: "pointer",
    borderBottom: "1px solid #f3f4f6",
    transition: "background 0.15s ease",
  },
  resultTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#1f2937",
    marginBottom: "4px",
  },
  resultDescription: {
    fontSize: "12px",
    color: "#6b7280",
    lineHeight: "1.4",
  },
};
