import { LexicalEditor } from "lexical";
import { useWP } from "@rnaga/wp-next-core/client/wp";

import * as types from "../../../../types";
import { hasDynamicAttributes } from "../../../dynamic-attributes/DynamicAttributes";
import { $generateHtmlFromNode, walkNodeWithWidgets } from "../../../lexical";
import { $isCollectionNode } from "../../collection/CollectionNode";
import {
  $isTemplateTextNode,
  $processTemplateText,
} from "../../template-text/TemplateTextNode";
import { DataFetchingPagination } from "../DataFetchingNode";
import { RELOAD_DYNAMIC_VALUE_COMMAND } from "../commands";

import type { WPLexicalNode } from "../../wp/types";

type WPHooks = ReturnType<typeof useWP>["wpHooks"];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extract data fetching node names from a template string.
 * Handles expressions like "${posts.title}" → "posts".
 * For pagination expressions like "${%pagination.posts.page}", extracts "posts"
 * (the data fetching node name embedded in the pagination key).
 */
const extractDataKeysFromTemplate = (template: string): string[] => {
  const keys = new Set<string>();
  const regex = /\$\{([^}]+)/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(template)) !== null) {
    const segments = match[1].trim().split(".");
    if (segments[0] === "%pagination") {
      const dataName = segments[1]?.trim();
      if (dataName) {
        keys.add(dataName);
      }
    } else {
      keys.add(segments[0]);
    }
  }

  return [...keys];
};

/**
 * Walk all nodes in the editor tree (including nodes inside WidgetNodes) and
 * build a map of reload data for dynamic attributes, template text nodes, and
 * optionally a specific collection, all keyed by CSS class name.
 *
 * @param editor - Root Lexical editor
 * @param options.dataFetchingName - When provided, only include dynamic attribute
 *   and template text entries that reference this data fetching node name.
 * @param options.collectionName - When provided, collect the CollectionNode with
 *   this name for a full HTML regeneration.
 */
const buildReloadMap = (
  editor: LexicalEditor,
  options?: {
    dataFetchingName?: string;
    collectionName?: string;
  }
): types.ReloadMap => {
  const dynamicAttributes: types.DynamicAttributeMap = {};
  const templateText: types.TemplateTextMap = {};
  const collections: types.CollectionMap = {};

  const { dataFetchingName, collectionName } = options ?? {};

  walkNodeWithWidgets(editor, (nodeEditor, node) => {
    nodeEditor.read(() => {
      // ---------------------------------------------------------------
      // Collection Nodes — full HTML regeneration
      // ---------------------------------------------------------------
      if (collectionName && $isCollectionNode(node)) {
        if (node.getName() !== collectionName) {
          return;
        }

        const cssClassName = node.__css?.getClassName();
        if (!cssClassName) {
          return;
        }

        collections[cssClassName] = {
          collectionNode: node,
          collectionEditor: nodeEditor,
        };

        // Collection's own children are re-generated by $generateHtmlFromNode,
        // so skip processing descendants for dynamic attrs / template text here.
        return;
      }

      // ---------------------------------------------------------------
      // Dynamic Attributes
      // ---------------------------------------------------------------
      if (hasDynamicAttributes(node) && node.__dynamicAttributes.hasRules()) {
        const wpNode = node as unknown as WPLexicalNode;
        const cssClassName = (wpNode as any).__css?.getClassName?.() as
          | string
          | undefined;

        if (!cssClassName) {
          return;
        }

        const entry = node.__dynamicAttributes.computeAttributes({
          node: wpNode,
        });

        if (dataFetchingName && !entry.dataKeys.includes(dataFetchingName)) {
          return;
        }

        dynamicAttributes[cssClassName] = {
          dataKeys: entry.dataKeys,
          attributes: {
            classNames: entry.classNames,
            allPossibleClassNames: entry.allPossibleClassNames,
            customAttributes: entry.customAttributes,
            allPossibleCustomAttributeKeys:
              entry.allPossibleCustomAttributeKeys,
            display: entry.display,
          },
        };
      }

      // ---------------------------------------------------------------
      // Template Text Nodes
      // ---------------------------------------------------------------
      if ($isTemplateTextNode(node)) {
        const wpNode = node as unknown as WPLexicalNode;
        const cssClassName = (wpNode as any).__css?.getClassName?.() as
          | string
          | undefined;

        if (!cssClassName) {
          return;
        }

        const template: string = (node as any).__template ?? "";
        if (!template) {
          return;
        }

        const dataKeys = extractDataKeysFromTemplate(template);

        if (dataFetchingName && !dataKeys.includes(dataFetchingName)) {
          return;
        }

        const content = $processTemplateText(template, { node: wpNode });

        templateText[cssClassName] = { dataKeys, content };
      }
    });
  });

  return { dynamicAttributes, templateText, collections };
};

// ---------------------------------------------------------------------------
// DOM application
// ---------------------------------------------------------------------------

/**
 * Apply a pre-built ReloadMap to the live DOM.
 *
 * Collections are applied first (full innerHTML replacement via
 * $generateHtmlFromNode) so that subsequent dynamic attribute and template
 * text patches operate on the freshly generated elements.
 *
 * Dynamic attribute updates:
 *  - display: sets/removes inline `display:none`
 *  - classNames: removes every class that appears in any rule first, then adds
 *    those from matched rules — so only dynamically-managed class names are
 *    touched; unrelated classes (e.g. from external scripts) are preserved.
 *  - customAttributes: removes all keys that exist in any rule first, then
 *    sets the keys that came from matched rules.
 *
 * Template text updates: replaces `innerHTML` with the processed content.
 */
const applyReloadMapToDOM = (reloadMap: types.ReloadMap): void => {
  const { dynamicAttributes, templateText, collections } = reloadMap;

  // 1. Collections — regenerate full inner HTML first so dynamic attr / template
  //    text patches below operate on the freshly inserted elements.
  for (const [cssClassName, entry] of Object.entries(collections)) {
    const element = document.querySelector(
      `.${cssClassName}`
    ) as HTMLElement | null;

    if (!element) {
      continue;
    }

    entry.collectionEditor.read(() => {
      const newElement = $generateHtmlFromNode(
        entry.collectionEditor,
        entry.collectionNode
      );

      if (!newElement) {
        return;
      }

      // Use replaceChildren to replace content while preserving the element.
      // This is better than innerHTML as it works with DOM nodes directly and
      // properly handles event listener cleanup.
      element.replaceChildren(...Array.from(newElement.childNodes));
    });
  }

  // 2. Dynamic attributes
  for (const [cssClassName, entry] of Object.entries(dynamicAttributes)) {
    const element = document.querySelector(
      `.${cssClassName}`
    ) as HTMLElement | null;

    if (!element) {
      continue;
    }

    const { attributes } = entry;

    // Display
    element.style.removeProperty("display");
    if (!attributes.display) {
      element.style.setProperty("display", "none");
    }

    // Class names — remove all that could have been set by any rule, then
    // add back only those from rules that currently match.
    for (const className of attributes.allPossibleClassNames) {
      element.classList.remove(className);
    }

    for (const className of attributes.classNames) {
      element.classList.add(className);
    }

    // Custom attributes — same remove-all-then-set-matched pattern.
    for (const key of attributes.allPossibleCustomAttributeKeys) {
      element.removeAttribute(key);
    }

    for (const [key, value] of Object.entries(attributes.customAttributes)) {
      element.setAttribute(key, value);
    }
  }

  // 3. Template text
  for (const [cssClassName, entry] of Object.entries(templateText)) {
    const element = document.querySelector(
      `.${cssClassName}`
    ) as HTMLElement | null;

    if (!element) {
      continue;
    }

    element.innerHTML = entry.content;
  }
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Flatten a ReloadMap's dynamicAttributes and templateText entries into a
 * consolidated nodes map keyed by CSS class name.
 *
 * When the same class name appears in both maps (rare but possible), dataNames
 * are merged via a Set so there are no duplicates.
 */
const buildNodesMap = (
  reloadMap: types.ReloadMap
): Record<string, types.DynamicValuesReloadedEntry> => {
  const nodes: Record<string, types.DynamicValuesReloadedEntry> = {};

  for (const [cssClassName, entry] of Object.entries(
    reloadMap.dynamicAttributes
  )) {
    nodes[cssClassName] = {
      dataNames: entry.dataKeys,
      attributes: entry,
      templateText: undefined,
    };
  }

  for (const [cssClassName, entry] of Object.entries(reloadMap.templateText)) {
    const existing = nodes[cssClassName];

    if (existing) {
      nodes[cssClassName] = {
        dataNames: [...new Set([...existing.dataNames, ...entry.dataKeys])],
        attributes: existing.attributes,
        templateText: entry,
      };
    } else {
      nodes[cssClassName] = {
        dataNames: entry.dataKeys,
        attributes: undefined,
        templateText: entry,
      };
    }
  }

  return nodes;
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Walk all nodes and return the dynamic-attribute map portion of the reload
 * map. Each entry's `computeAttributes` call already respects
 * `DynamicAttributes.__editorConfig`, so nodes with
 * `DYNAMIC_ATTRIBUTES_EDITOR_CONFIG_HIDDEN` set will return empty classNames /
 * customAttributes — the caller can apply the result to any document to clear
 * those effects.
 */
export const buildDynamicAttributeMap = (
  editor: LexicalEditor
): types.DynamicAttributeMap => {
  return buildReloadMap(editor).dynamicAttributes;
};

/**
 * Apply a pre-built dynamic-attribute map to a specific document.
 *
 * Follows the same remove-all-possible-then-add-matched pattern as
 * `applyReloadMapToDOM`, but accepts an explicit `Document` so callers can
 * target a preview iframe's `contentDocument` instead of the global
 * `document`.
 *
 * Safe to call with `null`/`undefined` — returns immediately when no document
 * is provided.
 */
export const applyDynamicAttributesToDocument = (
  doc: Document | null | undefined,
  dynamicAttributes: types.DynamicAttributeMap
): void => {
  if (!doc) {
    return;
  }

  for (const [cssClassName, entry] of Object.entries(dynamicAttributes)) {
    const element = doc.querySelector<HTMLElement>(`.${cssClassName}`);

    if (!element) {
      continue;
    }

    const { attributes } = entry;

    // Display
    element.style.removeProperty("display");
    if (!attributes.display) {
      element.style.setProperty("display", "none");
    }

    // Class names — remove all that could have been set by any rule, then
    // add back only those from rules that currently match.
    for (const className of attributes.allPossibleClassNames) {
      element.classList.remove(className);
    }

    for (const className of attributes.classNames) {
      element.classList.add(className);
    }

    // Custom attributes — same remove-all-then-set-matched pattern.
    for (const key of attributes.allPossibleCustomAttributeKeys) {
      element.removeAttribute(key);
    }

    for (const [key, value] of Object.entries(attributes.customAttributes)) {
      element.setAttribute(key, value);
    }
  }
};

/**
 * Re-evaluate dynamic attributes, template text nodes, and optionally a named
 * collection in the editor tree, then patch the live DOM to reflect current
 * data values.
 *
 * This is the client-side counterpart to the server-side SSR/preview pipeline.
 * Call it after any client-side data mutation (pagination, ReactDecorators, etc.)
 * to keep DOM elements in sync without a full page reload.
 *
 * After patching the DOM, fires RELOAD_DYNAMIC_VALUE_COMMAND via wpHooks (when
 * provided) so subscribers can react to any data-driven DOM update without
 * being coupled to a specific collection or pagination flow.
 *
 * @param editor - The root Lexical editor instance
 * @param options.dataFetchingName - Optional name of the data fetching node that
 *   was mutated. When provided, only dynamic attribute and template text nodes
 *   that reference this data source are updated, reducing unnecessary DOM work.
 *   When omitted, all such nodes are re-evaluated.
 * @param options.collectionName - Optional name of a CollectionNode whose full
 *   inner HTML should be regenerated. When omitted, no collection HTML is
 *   regenerated.
 * @param context.wpHooks - When provided, RELOAD_DYNAMIC_VALUE_COMMAND is fired
 *   after the DOM is patched.
 * @param context.query - Query that triggered the data fetch (defaults to {}).
 * @param context.fetchedData - The raw fetched data: [data, pagination] when
 *   pagination applies, [data] otherwise.
 */
export const reloadDynamicValues = (
  editor: LexicalEditor,
  options?: {
    dataFetchingName?: string;
    collectionName?: string;
  },
  context?: {
    wpHooks?: WPHooks;
    query?: Record<string, any>;
    fetchedData?: [any, DataFetchingPagination] | [any];
    dataFetchingId?: string;
  }
): void => {
  const reloadMap = buildReloadMap(editor, options);
  applyReloadMapToDOM(reloadMap);

  if (!context?.wpHooks) {
    return;
  }

  const payload: types.DynamicValuesReloadedPayload = {
    dataFetchingName: options?.dataFetchingName,
    targetCollection: options?.collectionName,
    dataFetchingId: context.dataFetchingId,
    query: context.query ?? {},
    fetchedData: context.fetchedData,
    nodes: buildNodesMap(reloadMap),
  };

  context.wpHooks.action.doCommand(RELOAD_DYNAMIC_VALUE_COMMAND, payload);
};
